context:
  name: haven-conf
  version: 0.1.0
  python_min: 3.10.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/haven_conf-${{ version }}.tar.gz
  sha256: d20dcd20c797f75781bc4e6eaecf42b78613fd2204b6c868cd8bf693a1ff34fa

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - flit = flit:main

requirements:
  host:
    - pip
    - python ${{ python_min }}
    - flit-core
  run:
    - fsspec
    - python >=${{ python_min }}
    - pyyaml

tests:
  - python:
      imports:
        - haven
  - requirements:
      run:
        - pip
        - python ${{ python_min }}
    script:
      - pip check

about:
  summary: A simple, flexible library for configuring python projects using dataclasses.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/jonmorton/haven

extra:
  recipe-maintainers:
    - jeongseok-meta
